# codemagic.yaml
# builds a .ipa
# Prerequisites:
# Save the base64-encoded provisioning profile and certificate to environment
# variables and decode them in the scripts as shown below.
workflows:
  my-workflow:
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Add signing certificate
        script: |
          set -e # exit on first failed command
          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
          keychain initialize
          keychain add-certificates \
              --certificate /tmp/certificate.p12 \
              --certificate-password ${CERTIFICATE_PASSWORD?}
      - name: Increment build number
        script: agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "io.codemagic.app" \
          --type IOS_APP_DEVELOPMENT \
          --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --workspace "${XCODE_WORKSPACE?}" \
                    --scheme "${XCODE_SCHEME?}"
    artifacts:
      - build/ios/ipa/*.ipa
